---
- name: Mettre à jour la liste des paquets Debian
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Mettre à niveau tous les paquets Debian
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
