---
- name: Mise à jour Debian – interactive
  hosts: "{{ target_hosts }}"
  become: true

  vars_prompt:
    - name: "target_hosts"
      prompt: "Quels hosts veux-tu mettre à jour ? (ex : webservers, 172.16.1.20, all)"
      private: false

  roles:
    - debian_update_upgrade
