---
- name: Installation interactive de Clonezilla Server
  hosts: all
  become: yes

  vars_prompt:
    - name: "drbl_iface"
      prompt: "Entrez l'interface réseau à utiliser (ex: eth0, ens18)"
      private: no

    - name: "drbl_use_dhcp"
      prompt: "Activer le serveur DHCP intégré de Clonezilla ? (oui/non)"
      private: no

    - name: "drbl_use_proxydhcp"
      prompt: "Activer le ProxyDHCP (recommandé si DHCP = non) ? (oui/non)"
      private: no

    - name: "drbl_image_repo"
      prompt: "Chemin du répertoire des images ? (/srv/clonezilla_images)"
      default: "/srv/clonezilla_images"
      private: no

  vars:
    drbl_use_dhcp_bool: "{{ drbl_use_dhcp | lower in ['oui','yes','true'] }}"
    drbl_use_proxydhcp_bool: "{{ drbl_use_proxydhcp | lower in ['oui','yes','true'] }}"

  roles:
    - role: clonezilla_server
