---
name: Lint

on:
  push:
    branches: [dev, main]
  pull_request:

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Lancer ansible-lint
        uses: ansible/ansible-lint@main
